include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - '**.freezed.dart'
    - '**.g.dart'
    - '**.gr.dart'
    - '**/generated_plugin_registrant.dart'

  plugins:
    - dart_code_metrics

  errors:
    empty_constructor_bodies: error
    missing_required_param: error
    always_use_package_imports: error
    avoid_types_as_parameter_names: error
    close_sinks: error
    unnecessary_statements: warning
    non_constant_identifier_names: warning

linter:
  rules:
    camel_case_types: true
    #    prefer_double_quotes: true
    avoid_empty_else: true
    constant_identifier_names: false
    use_key_in_widget_constructors: false
    prefer_relative_imports: true
    no_leading_underscores_for_local_identifiers: false
    non_constant_identifier_names: false
    implementation_imports: false

dart_code_metrics:
  #  anti-patterns:
  #    - long-method
  #    - long-parameter-list
  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    number-of-parameters: 8
    source-lines-of-code: 50
  metrics-exclude:
    - test/**
    - ios/**
    - android/**
  rules:
    no-boolean-literal-compare:
      severity: warning
    #     avoid-returning-widgets:
    #       severity: none
    prefer-conditional-expressions:
      severity: warning
    no-magic-number:
#     avoid-unused-parameters:
#       severity: warning



#   severity -> none, style, performance, warning, error.