import 'package:intl/intl.dart';
import 'package:json_annotation/json_annotation.dart';
import 'vn_delivery_box.dart';
import 'vn_delivery_order.dart';

import '../../../core/enum/delivery_bill_status.dart';


part 'bill_customer_detail.g.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
@JsonSerializable()
class BillCustomerDetailCustomer {
  int? id;
  String? name;
  String? phone;
  String? address;
  String? email;
  String? balance;
  String? note;
  String? nickName;
  int? shippingCost;
  String? idCustomer;
  int? creditAmount;
  bool? isSubcribeToEmailNotification;
  bool? isSubcribeToFcmNotification;
  String? gender;
  String? createdAt;
  String? updatedAt;

  BillCustomerDetailCustomer({
    this.id,
    this.name,
    this.phone,
    this.address,
    this.email,
    this.balance,
    this.note,
    this.nickName,
    this.shippingCost,
    this.idCustomer,
    this.creditAmount,
    this.isSubcribeToEmailNotification,
    this.isSubcribeToFcmNotification,
    this.gender,
    this.createdAt,
    this.updatedAt,
  });

  factory BillCustomerDetailCustomer.fromJson(Map<String, dynamic> json) =>
      _$BillCustomerDetailCustomerFromJson(json);

  Map<String, dynamic> toJson() => _$BillCustomerDetailCustomerToJson(this);
}

@JsonSerializable()
class BillCustomerDetail {
  int? id;
  String? code;
  @JsonKey(fromJson: _statusFromJson, toJson: _statusToJson,name: 'deliveryBillStatus')
  DeliveryStatus? deliveryBillStatus;
  String? customerAddress;
  String? customerPhone;
  bool? isConfirmedByCustomer;
  bool? isPackaged;
  bool? isCharged;
  int? createdById;
  List<BillCustomerDetailCustomer?>? customer;
  String? createdAt;
  String? updatedAt;
  String? name;
  String? email;
  List<VnDeliveryOrder?>? vnDeliveryOrder;
  List<VnDeliveryBox?>? vnDeliveryBoxes;
  double? totalTrackingMiningWeight;
  double? totalTrackingCalculationWeight;
  int? quantityTracking;
  int? trackingTotalMoney;

  BillCustomerDetail(
      {this.id,
        this.code,
        this.deliveryBillStatus,
        this.customerAddress,
        this.customerPhone,
        this.isConfirmedByCustomer,
        this.isPackaged,
        this.isCharged,
        this.createdById,
        this.customer,
        this.createdAt,
        this.updatedAt,
        this.name,
        this.email,
        this.vnDeliveryOrder,
        this.vnDeliveryBoxes,
        this.totalTrackingMiningWeight,
        this.totalTrackingCalculationWeight,
        this.quantityTracking,
        this.trackingTotalMoney});

  factory BillCustomerDetail.fromJson(Map<String, dynamic> json) =>
      _$BillCustomerDetailFromJson(json);

  Map<String, dynamic> toJson() => _$BillCustomerDetailToJson(this);

  static DeliveryStatus? _statusFromJson(String? value) =>
      DeliveryStatus.fromValue(value);

  static String? _statusToJson(DeliveryStatus? status) => status?.value;

  String get formattedTrackingTotalMoney {
    if (trackingTotalMoney == null) {
      return '0';
    }
    final formatter = NumberFormat("#,##0.##", "vi");
    return "${formatter.format(double.parse(trackingTotalMoney.toString()))}đ";
  }

  String get formattedTrackingTotalWeight {
    if (totalTrackingCalculationWeight == null) {
      return '0';
    }
    final formatter = NumberFormat("#,##0.##", "en_US");
    return formatter.format(double.parse(totalTrackingCalculationWeight.toString()));
  }

  String get formattedTrackingMiningWeight {
    if (totalTrackingMiningWeight == null) {
      return '0';
    }
    final formatter = NumberFormat("#,##0.##", "en_US");
    return formatter.format(double.parse(totalTrackingMiningWeight.toString()));
  }
}