import 'package:json_annotation/json_annotation.dart';

import '../../../core/enum/delivery_bill_status.dart';
import '../../../core/enum/orders_status.dart';
import '../../../modules/common_widget/const.dart';

part 'bill_of_lading.g.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///

@JsonSerializable()
class BillOfLadingVnDeliveryBillTracking {
  int? id;
  String? code;
  String? description;
  @JsonKey(fromJson: _statusFromJson, toJson: _statusToJson)
  OrderStatus? status;
  DateTime? importDate;
  DateTime? packedDate;
  String? exploitedDate;
  bool? isRepack;
  bool? isSplit;
  bool? isDeleted;
  @JsonKey(fromJson: _statusFromJson, toJson: _statusToJson)
  OrderStatus? exploitStatus;
  String? trackingMiningWeight;
  String? trackingCalculationWeight;
  String? trackingBarrelCoefficient;
  String? trackingShippingCost;
  String? trackingShippingFee;
  String? trackingDeliveryFee;
  String? trackingOtherFee;
  int? trackingDiscountAmount;
  String? trackingTotalMoney;
  int? trackingAmount;
  String? orderId;
  String? price;
  DateTime? createdAt;
  DateTime? updatedAt;
  bool? isRenamed;
  int? whTrackingId;
  String? vnPackedDate;
  String? vnImportDate;
  String? vnExportDate;
  int? vnPackedById;
  String? productName;

  BillOfLadingVnDeliveryBillTracking({
    this.id,
    this.code,
    this.description,
    this.status,
    this.importDate,
    this.packedDate,
    this.exploitedDate,
    this.isRepack,
    this.isSplit,
    this.isDeleted,
    this.exploitStatus,
    this.trackingMiningWeight,
    this.trackingCalculationWeight,
    this.trackingBarrelCoefficient,
    this.trackingShippingCost,
    this.trackingShippingFee,
    this.trackingDeliveryFee,
    this.trackingOtherFee,
    this.trackingDiscountAmount,
    this.trackingTotalMoney,
    this.trackingAmount,
    this.orderId,
    this.price,
    this.createdAt,
    this.updatedAt,
    this.isRenamed,
    this.whTrackingId,
    this.vnPackedDate,
    this.vnImportDate,
    this.vnExportDate,
    this.vnPackedById,
    this.productName,
  });

  factory BillOfLadingVnDeliveryBillTracking.fromJson(
          Map<String, dynamic> json) =>
      _$BillOfLadingVnDeliveryBillTrackingFromJson(json);

  Map<String, dynamic> toJson() =>
      _$BillOfLadingVnDeliveryBillTrackingToJson(this);

  static OrderStatus? _statusFromJson(String? value) =>
      OrderStatus.fromValue(value);

  static String? _statusToJson(OrderStatus? status) => status?.value;
}

@JsonSerializable()
class BillOfLadingVnDeliveryBill {
  int? id;
  String? code;
  @JsonKey(
      fromJson: _deliveryBillStatusFromJson, toJson: _deliveryBillStatusToJson)
  DeliveryStatus? deliveryBillStatus;
  String? customerAddress;
  String? customerPhone;
  bool? isConfirmedByCustomer;
  bool? isPackaged;
  bool? isCharged;
  int? createdById;
  String? createdAt;
  String? updatedAt;
  String? name;
  String? email;
  List<BillOfLadingVnDeliveryBillTracking?>? tracking;

  BillOfLadingVnDeliveryBill({
    this.id,
    this.code,
    this.deliveryBillStatus,
    this.customerAddress,
    this.customerPhone,
    this.isConfirmedByCustomer,
    this.isPackaged,
    this.isCharged,
    this.createdById,
    this.createdAt,
    this.updatedAt,
    this.name,
    this.email,
    this.tracking,
  });

  factory BillOfLadingVnDeliveryBill.fromJson(Map<String, dynamic> json) =>
      _$BillOfLadingVnDeliveryBillFromJson(json);

  Map<String, dynamic> toJson() => _$BillOfLadingVnDeliveryBillToJson(this);

  static DeliveryStatus? _deliveryBillStatusFromJson(String? value) =>
      DeliveryStatus.fromValue(value);

  static String? _deliveryBillStatusToJson(DeliveryStatus? status) =>
      status?.value;
}

@JsonSerializable()
class BillOfLadingVnDeliveryBoxesDeliveredBy {
  int? id;
  String? username;
  String? email;
  String? provider;
  String? password;
  String? resetPasswordToken;
  String? confirmationToken;
  bool? confirmed;
  bool? blocked;
  String? phone;
  String? type;
  String? fullname;
  String? confirmPassword;
  String? tmpPassword;
  String? createdAt;
  String? updatedAt;
  String? createdById;
  String? updatedById;
  String? code;
  String? avatarUrl;

  BillOfLadingVnDeliveryBoxesDeliveredBy({
    this.id,
    this.username,
    this.email,
    this.provider,
    this.password,
    this.resetPasswordToken,
    this.confirmationToken,
    this.confirmed,
    this.blocked,
    this.phone,
    this.type,
    this.fullname,
    this.confirmPassword,
    this.tmpPassword,
    this.createdAt,
    this.updatedAt,
    this.createdById,
    this.updatedById,
    this.code,
    this.avatarUrl,
  });

  factory BillOfLadingVnDeliveryBoxesDeliveredBy.fromJson(
          Map<String, dynamic> json) =>
      _$BillOfLadingVnDeliveryBoxesDeliveredByFromJson(json);

  Map<String, dynamic> toJson() => _$BillOfLadingVnDeliveryBoxesDeliveredByToJson(this);
}

@JsonSerializable()
class BillOfLadingVnDeliveryBoxes {
  int? id;
  String? code;
  int? vnDeliveryOrderId;
  int? deliveredById;
  String? receivedDate;
  String? deliveredDate;
  String? note;
  int? status;
  BillOfLadingVnDeliveryBoxesDeliveredBy? deliveredBy;

  BillOfLadingVnDeliveryBoxes(
      {this.id,
      this.code,
      this.vnDeliveryOrderId,
      this.deliveredById,
      this.receivedDate,
      this.deliveredDate,
      this.note,
      this.status,
      this.deliveredBy});

  factory BillOfLadingVnDeliveryBoxes.fromJson(Map<String, dynamic> json) =>
      _$BillOfLadingVnDeliveryBoxesFromJson(json);

  Map<String, dynamic> toJson() => _$BillOfLadingVnDeliveryBoxesToJson(this);

  String get formattedReceivedDate {
    return Const.convertDate(receivedDate);
  }

  String get formattedDeliveredDate {
    return Const.convertDate(deliveredDate);
  }
}

@JsonSerializable()
class BillOfLadingVnDeliveryUnit {
  int? id;
  String? name;
  String? code;
  String? logoUrl;
  int? status;

  BillOfLadingVnDeliveryUnit({
    this.id,
    this.name,
    this.code,
    this.logoUrl,
    this.status,
  });

  factory BillOfLadingVnDeliveryUnit.fromJson(Map<String, dynamic> json) =>
      _$BillOfLadingVnDeliveryUnitFromJson(json);

  Map<String, dynamic> toJson() => _$BillOfLadingVnDeliveryUnitToJson(this);
}

@JsonSerializable()
class BillOfLading {
  int? id;
  String? code;
  int? quantity;
  int? deliveryBillId;
  int? status;
  int? vnDeliveryUnitId;
  BillOfLadingVnDeliveryUnit? vnDeliveryUnit;
  List<BillOfLadingVnDeliveryBoxes?>? vnDeliveryBoxes;
  BillOfLadingVnDeliveryBill? vnDeliveryBill;

  BillOfLading({
    this.id,
    this.code,
    this.quantity,
    this.deliveryBillId,
    this.status,
    this.vnDeliveryUnitId,
    this.vnDeliveryUnit,
    this.vnDeliveryBoxes,
    this.vnDeliveryBill,
  });

  factory BillOfLading.fromJson(Map<String, dynamic> json) =>
      _$BillOfLadingFromJson(json);

  Map<String, dynamic> toJson() => _$BillOfLadingToJson(this);
}


class BolAdd {
  int? id;
  String? code;
  int? quantity;
  int? deliveryBillId;
  int? status;
  int? vnDeliveryUnitId;

  BolAdd({
    this.id,
    this.code,
    this.quantity,
    this.deliveryBillId,
    this.status,
    this.vnDeliveryUnitId,
  });
  BolAdd.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    code = json['code']?.toString();
    quantity = json['quantity']?.toInt();
    deliveryBillId = json['deliveryBillId']?.toInt();
    status = json['status']?.toInt();
    vnDeliveryUnitId = json['vnDeliveryUnitId']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['code'] = code;
    data['quantity'] = quantity;
    data['deliveryBillId'] = deliveryBillId;
    data['status'] = status;
    data['vnDeliveryUnitId'] = vnDeliveryUnitId;
    return data;
  }
}


class CodePacked {
  int? id;
  String? code;

  CodePacked({this.id, this.code});
}