import 'package:json_annotation/json_annotation.dart';
import 'package:vncss/app/core/enum/orders_status.dart';

import 'box.dart';
part 'orders.g.dart';
///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///

@JsonSerializable()
class OrdersVnPackedBy {
  int? id;
  String? username;
  String? email;
  String? phone;
  String? fullname;
  String? avatarUrl;

  OrdersVnPackedBy({
    this.id,
    this.username,
    this.email,
    this.phone,
    this.fullname,
    this.avatarUrl,
  });
  factory OrdersVnPackedBy.fromJson(Map<String, dynamic> json) => _$OrdersVnPackedByFromJson(json);
  Map<String, dynamic> toJson() => _$OrdersVnPackedByToJson(this);
}

@JsonSerializable()
class OrdersExploitedBy {

  int? id;
  String? username;
  String? email;
  String? phone;
  String? fullname;

  OrdersExploitedBy({
    this.id,
    this.username,
    this.email,
    this.phone,
    this.fullname,
  });
 factory OrdersExploitedBy.fromJson(Map<String, dynamic> json) => _$OrdersExploitedByFromJson(json);
  Map<String, dynamic> toJson() => _$OrdersExploitedByToJson(this);
}

@JsonSerializable()
class OrdersWarehouseVn {

  int? id;
  String? name;

  OrdersWarehouseVn({
    this.id,
    this.name,
  });
factory  OrdersWarehouseVn.fromJson(Map<String, dynamic> json) => _$OrdersWarehouseVnFromJson(json);
  Map<String, dynamic> toJson() => _$OrdersWarehouseVnToJson(this);
}

@JsonSerializable()
class OrdersDeliveryBill {

  int? id;
  String? code;
  String? createdAt;

  OrdersDeliveryBill({
    this.id,
    this.code,
    this.createdAt,
  });
 factory OrdersDeliveryBill.fromJson(Map<String, dynamic> json) => _$OrdersDeliveryBillFromJson(json);
  Map<String, dynamic> toJson() => _$OrdersDeliveryBillToJson(this);
}

@JsonSerializable()
class OrdersCustomerTags {


  int? id;
  String? name;
  String? color;

  OrdersCustomerTags({
    this.id,
    this.name,
    this.color,
  });
factory  OrdersCustomerTags.fromJson(Map<String, dynamic> json) => _$OrdersCustomerTagsFromJson(json);
  Map<String, dynamic> toJson() => _$OrdersCustomerTagsToJson(this);
}

@JsonSerializable()
class OrdersCustomerShippingCost {

  int? id;
  String? configKey;
  String? configValue;

  OrdersCustomerShippingCost({
    this.id,
    this.configKey,
    this.configValue,
  });
factory  OrdersCustomerShippingCost.fromJson(Map<String, dynamic> json) => _$OrdersCustomerShippingCostFromJson(json);
  Map<String, dynamic> toJson() => _$OrdersCustomerShippingCostToJson(this);
}

@JsonSerializable()
class OrdersCustomer {

  int? id;
  String? name;
  String? phone;
  String? address;
  String? email;
  String? nickName;
  OrdersCustomerShippingCost? shippingCost;
  List<OrdersCustomerTags?>? tags;
  String? idCustomer;
  bool? isSubcribeToEmailNotification;
  bool? isSubcribeToFcmNotification;

  OrdersCustomer({
    this.id,
    this.name,
    this.phone,
    this.address,
    this.email,
    this.nickName,
    this.shippingCost,
    this.tags,
    this.idCustomer,
    this.isSubcribeToEmailNotification,
    this.isSubcribeToFcmNotification,
  });
 factory OrdersCustomer.fromJson(Map<String, dynamic> json) => _$OrdersCustomerFromJson(json);
  Map<String, dynamic> toJson() => _$OrdersCustomerToJson(this);
}


@JsonSerializable()
class OrdersBusinessPartner {
  int? id;
  String? name;

  OrdersBusinessPartner({
    this.id,
    this.name,
  });
 factory OrdersBusinessPartner.fromJson(Map<String, dynamic> json) => _$OrdersBusinessPartnerFromJson(json);
  Map<String, dynamic> toJson() => _$OrdersBusinessPartnerToJson(this);
}

@JsonSerializable()
class OrdersTrackingType {

  int? id;
  String? name;
  String? color;

  OrdersTrackingType({
    this.id,
    this.name,
    this.color,
  });
 factory OrdersTrackingType.fromJson(Map<String, dynamic> json) => _$OrdersTrackingTypeFromJson(json);
  Map<String, dynamic> toJson() => _$OrdersTrackingTypeToJson(this);
}

@JsonSerializable()
class Orders {
  int? id;
  String? code;
  OrdersTrackingType? trackingType;
  String? description;
  OrdersBusinessPartner? businessPartner;
  @JsonKey(fromJson: _statusFromJson, toJson: _statusToJson)
  OrderStatus? status;
  String? exploitedDate;
  Box? box;
  Box? awb;
  OrdersCustomer? customer;
  bool? isDeleted;
  String? imageUrl;
  String? note;
  @JsonKey(fromJson: _exploitStatusFromJson, toJson: _exploitStatusToJson)
  OrderStatus? exploitStatus;
  String? trackingMiningWeight;
  String? trackingCalculationWeight;
  String? trackingBarrelCoefficient;
  String? trackingShippingCost;
  String? trackingShippingFee;
  String? trackingSurcharge;
  String? trackingDeliveryFee;
  String? trackingOtherFee;
  int? trackingDiscountAmount;
  String? trackingTotalMoney;
  OrdersDeliveryBill? deliveryBill;
  int? trackingAmount;
  String? orderId;
  OrdersWarehouseVn? warehouseVn;
  OrdersExploitedBy? exploitedBy;
  String? price;
  String? createdAt;
  String? updatedAt;
  bool? isRenamed;
  String? vnPackedDate;
  String? vnImportDate;
  String? vnExportDate;
  int? vnPackedById;
  String? productName;
  OrdersVnPackedBy? vnPackedBy;

  Orders({
    this.id,
    this.code,
    this.trackingType,
    this.description,
    this.businessPartner,
    this.status,
    this.exploitedDate,
    this.box,
    this.awb,
    this.customer,
    this.isDeleted,
    this.imageUrl,
    this.note,
    this.exploitStatus,
    this.trackingMiningWeight,
    this.trackingCalculationWeight,
    this.trackingBarrelCoefficient,
    this.trackingShippingCost,
    this.trackingShippingFee,
    this.trackingSurcharge,
    this.trackingDeliveryFee,
    this.trackingOtherFee,
    this.trackingDiscountAmount,
    this.trackingTotalMoney,
    this.deliveryBill,
    this.trackingAmount,
    this.orderId,
    this.warehouseVn,
    this.exploitedBy,
    this.price,
    this.createdAt,
    this.updatedAt,
    this.isRenamed,
    this.vnPackedDate,
    this.vnImportDate,
    this.vnExportDate,
    this.vnPackedById,
    this.productName,
    this.vnPackedBy,
  });
factory  Orders.fromJson(Map<String, dynamic> json) => _$OrdersFromJson(json);
  Map<String, dynamic> toJson() => _$OrdersToJson(this);

  static OrderStatus? _statusFromJson(String? value) => OrderStatus.fromValue(value);

  static String? _statusToJson(OrderStatus? status) => status?.value;

  static OrderStatus? _exploitStatusFromJson(String? value) => OrderStatus.fromValue(value);

  static String? _exploitStatusToJson(OrderStatus? exploitStatus) => exploitStatus?.value;

}
