import 'package:json_annotation/json_annotation.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
part 'staff_detail.g.dart';
@JsonSerializable()
class StaffDetailBusinessPartner {

  int? id;
  String? name;
  String? address;
  String? phone;
  String? email;
  String? uid;
  bool? isSyncing;
  String? syncStatus;
  String? message;
  String? lastSync;
  String? createdAt;
  String? updatedAt;
  String? createdById;
  String? updatedById;

  StaffDetailBusinessPartner({
    this.id,
    this.name,
    this.address,
    this.phone,
    this.email,
    this.uid,
    this.isSyncing,
    this.syncStatus,
    this.message,
    this.lastSync,
    this.createdAt,
    this.updatedAt,
    this.createdById,
    this.updatedById,
  });
  factory StaffDetailBusinessPartner.fromJson(Map<String, dynamic> json) => _$StaffDetailBusinessPartnerFromJson(json);
  Map<String, dynamic> toJson()=> _$StaffDetailBusinessPartnerToJson(this);
}

@JsonSerializable()
class StaffDetailRole {

  int? id;
  String? name;
  String? type;
  bool? isDelete;
  List<String?>? actions;

  StaffDetailRole({
    this.id,
    this.name,
    this.type,
    this.isDelete,
    this.actions,
  });
  factory StaffDetailRole.fromJson(Map<String, dynamic> json) => _$StaffDetailRoleFromJson(json);
  Map<String, dynamic> toJson()=> _$StaffDetailRoleToJson(this);
}

@JsonSerializable()
class StaffDetailModel {

  int? id;
  String? username;
  StaffDetailRole? role;
  String? email;
  String? type;
  bool? confirmed;
  bool? blocked;
  String? phone;
  String? fullname;
  StaffDetailBusinessPartner? businessPartner;
  StaffWarehouseVN? warehouseVN;
  String? createdById;
  String? avatarUrl;
  String? provider;
  String? createdAt;
  String? updatedAt;
  String? updatedById;
  String? code;

  StaffDetailModel({
    this.id,
    this.username,
    this.role,
    this.email,
    this.type,
    this.confirmed,
    this.blocked,
    this.phone,
    this.fullname,
    this.businessPartner,
    this.warehouseVN,
    this.createdById,
    this.avatarUrl,
    this.provider,
    this.createdAt,
    this.updatedAt,
    this.updatedById,
    this.code,
  });
  factory StaffDetailModel.fromJson(Map<String, dynamic> json) => _$StaffDetailModelFromJson(json);
  Map<String, dynamic> toJson()=> _$StaffDetailModelToJson(this);
}

@JsonSerializable()
class StaffWarehouseVN {

  int? id;
  String? name;

  StaffWarehouseVN({
    this.id,
    this.name,
  });
  factory StaffWarehouseVN.fromJson(Map<String, dynamic> json) => _$StaffWarehouseVNFromJson(json);
  Map<String, dynamic> toJson()=> _$StaffWarehouseVNToJson(this);
}
