///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class TrackingDeliveryBill {
/*
{
  "id": 10097,
  "code": "DPOP07052400002",
  "createdAt": "2024-05-07T10:12:33.281Z"
}
*/

  int? id;
  String? code;
  String? createdAt;

  TrackingDeliveryBill({
    this.id,
    this.code,
    this.createdAt,
  });
  TrackingDeliveryBill.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    code = json['code']?.toString();
    createdAt = json['createdAt']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['code'] = code;
    data['createdAt'] = createdAt;
    return data;
  }
}
